/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include<opencv2/opencv.hpp>
#include<stdio.h>
/* Header for class android_com_ndkopencvtest_OpenCvNative */
using namespace cv;
using namespace std;

#ifndef _Included_android_com_ndkopencvtest_OpenCvNative
#define _Included_android_com_ndkopencvtest_OpenCvNative
#ifdef __cplusplus

extern "C" {
#endif
/*
 * Class:     android_com_ndkopencvtest_OpenCvNative
 * Method:    convertGray
 * Signature: (JJ)I
 */

 int toGray(Mat img,Mat& gray);

JNIEXPORT jint JNICALL Java_android_com_ndkopencvtest_OpenCvNative_convertGray
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
