/* DO NOT EDIT THIS FILE - it is machine generated */
#include <android_com_ndkopencvtest_OpenCvNative.h>

JNIEXPORT jint JNICALL Java_android_com_ndkopencvtest_OpenCvNative_convertGray
  (JNIEnv *, jclass, jlong addrRgba, jlong addrGray){
    Mat &mRgb = *(Mat*)addrRgba;
    Mat &mGray= *(May*)addrGray;
    int conv;
    jint retval;
    conv = toGray(mRgb,mGray);
    retval=(jint)conv;
    return retval;

  }

  int toGray(Mat img,Mat& gray){
    cvtColor(img,gray,CV_RGRA2RAY);
    if(gray.rows==img.rows && gray.cols==img.cols)
    return 1;
    return 0;

  }

